science_selection/application/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('application/', views.CreateApplicationView.as_view(), name='create_application'),

    path('application/<int:pk>/', views.ApplicationView.as_view(), name='application'),
    path('application/<int:pk>/edit/', views.EditApplicationView.as_view(), name='edit_application'),
    path('application/<int:pk>/direction/', views.ChooseDirectionInAppView.as_view(), name='choose_app_direction'),
    path('application/<int:pk>/competence/', views.ChooseCompetenceInAppView.as_view(), name='choose_app_competence'),
    path('application/<int:pk>/documents/', views.DocumentsInAppView.as_view(), name='app_documents'),
    path('application/<int:pk>/word/', views.CreateWordAppView.as_view(), name='create_word_app'),
    path('application/<int:pk>/add_note/', views.EditApplicationNote.as_view(), name='add_application_note'),
    path('application/<int:pk>/unsuitable/', views.AddAppToUnsuitable.as_view(), name='add_to_unsuitable'),
    path('application/list/', views.ApplicationListView.as_view(), name='application_list'),
    path('application/list/download/', views.ApplicationsDownloadingView.as_view(), name='downloading_applications'),
    path('application/<int:pk>/finished/', views.ChangeAppFinishedView.as_view(), name='change_finished'),
    path('application/list/service-document/', views.CreateServiceDocumentView.as_view(),
         name='create_word_service_document'),

    path('competence/add/<int:direction_id>/', views.AddCompetencesView.as_view(), name='add_competences'),
    path('competence/list/', views.CompetenceListView.as_view(), name='competence_list'),
    path('competence/delete/<int:competence_id>/<int:direction_id>/', views.DeleteCompetenceView.as_view(),
         name='delete_competence'),
    path('competence/create/', views.CreateCompetenceView.as_view(), name='create_competence'),
    path('documents/templates/delete/<int:file_id>/', views.DeleteFileView.as_view(), name='delete_file'),
    path('documents/templates/', views.MasterFileTemplatesView.as_view(), name='documents_templates'),
    path('documents/<int:file_id>/download/', views.DownloadFileView.as_view(), name='download_documents'),
    path('booking/<int:pk>/', views.BookMemberView.as_view(), name='book_member'),
    path('booking/delete/<int:pk>/<int:aff_id>/', views.UnBookMemberView.as_view(), name='un-book_member'),
    path('wishlist/add/<int:pk>/', views.AddInWishlistView.as_view(), name='add_in_wishlist'),
    path('wishlist/delete/<int:pk>/', views.DeleteFromWishlistView.as_view(), name='delete_from_wishlist'),
    path('work-group/list/', views.WorkGroupsListView.as_view(), name='work_group_list'),
    path('work-group/delete/<int:group_id>/', views.DeleteWorkGroupView.as_view(), name='delete_work_group'),
    path('work-group/<int:pk>/', views.WorkGroupView.as_view(), name='work_group'),
    path('work-group/remove-application/<int:app_id>/<int:group_id>/', views.RemoveApplicationWorkGroupView.as_view(),
         name='remove_app_from_group'),
    path('work-list/', views.WorkingListView.as_view(), name='work_list'),
    path('work-list/export/', views.ExportWorkListView.as_view(), name='export_work_list'),
    path('application/set-work-group/<int:app_id>/', views.ChangeWorkGroupView.as_view(), name='change_work_group'),

    path('search/universities/', views.ajax_search_info_in_db_tables, name='ajax_search_universities'),
    path('search/specialization/', views.ajax_search_info_in_db_tables, name='ajax_search_specialization'),
    path('search/commissariat/', views.ajax_search_info_in_db_tables, name='ajax_search_commissariat'),
    path('search/competencies/', views.CompetenceAutocomplete.as_view(), name='search_competencies', ),
]

science_selection/engine/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from account.views import HomeMasterView, HomeView, HomeSlaveView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls')),
                  path('app/', include('application.urls')),
                  path('test/', include('testing.urls')),
                  path('', HomeView.as_view(), name='home'),
                  path('master/', HomeMasterView.as_view(), name='home_master'),
                  path('operator/', HomeSlaveView.as_view(), name='home_slave'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

science_selection/science_selection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('application.urls'))
]

science_selection/application/models.py
import datetime

from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from utils import constants as const
from account.models import Member, Affiliation


def validate_draft_year(value: int):
    if value < datetime.date.today().year:
        raise ValidationError(_(f'Год призыва {value} раньше текущего'))


class WorkGroup(models.Model):
    """Рабочая группа, в которую происходит распрежедение забронированных заявок"""
    name = models.CharField(max_length=256, verbose_name='Название рабочей группы')
    affiliation = models.ForeignKey(Affiliation, verbose_name="Принадлежность", related_name='work_group',
                                    on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Описание рабочей группы', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рабочая группа'
        verbose_name_plural = 'Рабочие группы'


class Application(models.Model):
    """Заявка кандидата в операторы"""
    season = [
        (1, 'Весна'),
        (2, 'Осень')
    ]
    hidden_fields = ['compliance_prior_direction', 'compliance_additional_direction',
                     'postgraduate_additional_direction', 'postgraduate_prior_direction']

    member = models.OneToOneField(Member, on_delete=models.CASCADE, verbose_name='Пользователь',
                                  related_name='application')
    competencies = models.ManyToManyField('Competence', verbose_name='Выбранные компетенции',
                                          through='ApplicationCompetencies', blank=True)
    directions = models.ManyToManyField('Direction', verbose_name='Выбранные направления', blank=True,
                                        related_name='application')
    birth_day = models.DateField(verbose_name='Дата рождения')
    birth_place = models.CharField(max_length=128, verbose_name='Место рождения', help_text='Область, город')
    nationality = models.CharField(max_length=128, verbose_name='Гражданство')
    military_commissariat = models.CharField(max_length=128, verbose_name='Военный комиссариат')
    group_of_health = models.CharField(max_length=32, verbose_name='Группа здоровья')
    draft_year = models.IntegerField(verbose_name='Год призыва', validators=[validate_draft_year])
    draft_season = models.IntegerField(choices=season, verbose_name='Сезон призыва')
    ready_to_secret = models.BooleanField(default=False, verbose_name='Готовность к секретности',
                                          help_text='Готовность гражданина к оформлению допуска к сведениям, содержащим государственную тайну, по 3 форме')
    scientific_achievements = models.TextField(blank=True, verbose_name='Научные достижения',
                                               help_text='Участие в конкурсах, олимпиадах, издательской деятельности, '
                                                         'научно-практические конференции, наличие патентов на изобретения, '
                                                         'свидетельств о регистрации программ, свидетельств о рационализаторских предложениях и т.п.')
    scholarships = models.TextField(blank=True, verbose_name='Стипендии',
                                    help_text='Наличие грантов, именных премий, именных стипендий и т.п.')
    candidate_exams = models.TextField(blank=True, verbose_name='Кандидатские экзамены',
                                       help_text='Наличие оформленного соискательства ученой степени и сданных экзаменов кандидатского минимума')
    sporting_achievements = models.TextField(blank=True, verbose_name='Спортивные достижения',
                                             help_text='Наличие спортивных достижений и разрядов')
    hobby = models.TextField(blank=True, verbose_name='Хобби', help_text='Увлечения и хобби')
    other_information = models.TextField(blank=True, verbose_name='Дополнительная информация')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    fullness = models.IntegerField(default=0, verbose_name='Процент заполненности')
    final_score = models.FloatField(default=0, verbose_name='Итоговая оценка заявки')
    is_final = models.BooleanField(default=False, verbose_name='Законченность анкеты')
    unsuitable = models.BooleanField(default=False, verbose_name='Подходит или нет по его данным: средний балл и т.д.')
    work_group = models.ForeignKey(WorkGroup, on_delete=models.SET_NULL, blank=True, null=True,
                                   verbose_name="Рабочая группа",
                                   related_name='application')
    # дальше идут новые поля для калькулятора
    international_articles = models.BooleanField(default=False,
                                                 verbose_name="Наличие опубликованных научных статей в международных изданиях")
    patents = models.BooleanField(default=False, verbose_name="Наличие патентов на изобретения и полезные модели")
    vac_articles = models.BooleanField(default=False,
                                       verbose_name="Наличие опубликованных научных статей в научных изданиях, рекомендуемых ВАК")
    innovation_proposals = models.BooleanField(default=False,
                                               verbose_name="Наличие свидетельств нарационализаторские предложения")
    rinc_articles = models.BooleanField(default=False,
                                        verbose_name="Наличие опубликованных научных статей в изданиях РИНЦ")
    evm_register = models.BooleanField(default=False,
                                       verbose_name="Наличие свидетельств о регистрации баз данных и программ для ЭВМ")
    international_olympics = models.BooleanField(default=False,
                                                 verbose_name="Наличие призовых мест на международных олимпиадах")
    president_scholarship = models.BooleanField(default=False,
                                                verbose_name="Стипендиат государственных стипендий Президента Российской Федерации")
    country_olympics = models.BooleanField(default=False,
                                           verbose_name="Наличие призовых мест на олимпиадах всероссийского уровня")
    government_scholarship = models.BooleanField(default=False,
                                                 verbose_name="Стипендиат государственных стипендий Правительства Российской Федерации")
    military_grants = models.BooleanField(default=False,
                                          verbose_name="Обладательгрантов по научным работам, имеющим прикладное значение для Минобороны России, которые подтверждены органами военного управления")
    region_olympics = models.BooleanField(default=False,
                                          verbose_name="Наличие призовых мест на олимпиадах областного уровня")
    city_olympics = models.BooleanField(default=False,
                                        verbose_name="Наличие призовых мест на олимпиадах на уровне города")
    commercial_experience = models.BooleanField(default=False,
                                                verbose_name="Наличие опыта работы по специальности в коммерческих предприятиях (не менее 1 года)")
    opk_experience = models.BooleanField(default=False,
                                         verbose_name="Наличие опыта работы по специальности на предприятиях ОПК (не менее 1 года)")
    science_experience = models.BooleanField(default=False,
                                             verbose_name="Наличие опыта работы по специальности в научных организациях (подразделениях) на должностях научных сотрудников (не менее 1 года)")
    military_sport_achievements = models.BooleanField(default=False,
                                                      verbose_name="Наличие спортивных достижений по военно-прикладным видам спорта, в том числе выполнение нормативов ГТО")

    sport_achievements = models.BooleanField(default=False,
                                             verbose_name="Наличие спортивных достижений по иным видам спорта")

    # поля только для мастера
    compliance_prior_direction = models.BooleanField(default=False,
                                                     verbose_name="Соответствие приоритетному направлению высшего образования")
    compliance_additional_direction = models.BooleanField(default=False,
                                                          verbose_name="Соответствие дополнительному направлению высшего образования")
    postgraduate_additional_direction = models.BooleanField(default=False,
                                                            verbose_name="Наличие ученой степени по специальности, не соответствующей профилю научных исследований научной роты")
    postgraduate_prior_direction = models.BooleanField(default=False,
                                                       verbose_name="Наличие ученой степени по специальности, соответствующей профилю научных исследований научной роты")

    class Meta:
        ordering = ['create_date']
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"

    def check_military_commissariat(self):
        return True if MilitaryCommissariat.objects.filter(name=self.military_commissariat) else False

    def get_filed_blocks(self):
        return {
            'Основные данные': True,
            'Образование': self.education.all().exists(),
            'Направления': self.directions.all().exists(),
            'Компетенции': self.competencies.all().exists(),
            'Загруженные файлы': File.objects.filter(member=self.member).exists(),
        }

    def get_last_education(self):
        """
        Получение последнего образования
        :return: объект Education
        """
        return self.education.all().order_by('-end_year').first()

    def calculate_fullness(self) -> int:
        """

science_selection/application/templates/application/application_choose.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Создание заявки
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}


<form action="{% url 'choose_direction' %}" method="POST">
  {% csrf_token %}
  <div class="col-md-8 offset-2 row row-cols-1 row-cols-md-3 mt-4">
  {% for direction in directions %}
  <div class="col mb-4">
    <div class="card h-100">
      <img src="{{ direction.image_url }}" class="card-img-top" alt="{{ direction.name }}">
      <div class="card-body">
        <h5 class="card-title"> {{ direction.name }} </h5>
        <p class="card-text"> {{ direction.description }} </p>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" name="direction" id="{{ direction.name }}" value="{{ direction.id }}" {% if direction.id in selected_directions %} checked {% endif %}>
          <label class="custom-control-label" for="{{direction.name }}"><small class="text-muted">Выбрать направление</small></label>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
  <button type="submit" class="w-10 btn btn-primary justify-content-center" style="margin-left: 45%;">Сохранить</button>
</form>


{% endblock %}

science_selection/application/templates/application/application_competence_choose.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Выбор компетенций
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}

<div class="w-50 bg-white list-group-item border-top-0" style="margin-left: 25%;">
    {% if msg %}
        <div class="btn w-50" style="margin-left: 25%"> {{ msg }}
            {% if user.member.is_slave %}
                <button type="button" class="btn btn-outline-primary">
                    <a href="{% url name pk %}">Выбрать</a>
                </button>
            {% endif %}
        </div>
    {% else %}
        <div class="mb-2">
            {% if user.member.is_master %}
                <h5 class="text-center">Выбранные кандидатом компетенции</h5>
            {% elif user.member.is_slave %}
                <h5 class="text-center">Оцените свой уровень знаний имеющихся компетенций</h5>
            {% endif %}
            <ul class="list-group list-group-flush rounded">
                {% for level in levels %}
                    <li class="list-group-item lead bg-info bg-opacity-10">
                        {{ level.0 }} - {{ level.1 }}
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if not blocked %}
            <form action="{% url 'choose_app_competence' pk %}" method="POST">
                {% csrf_token %}
                <div class="accordion accordion-flush">
                    {% include 'application/includes/app_competencies_list.html' %}
                </div>
                <button type="submit" class="w-10 btn btn-outline-dark justify-content-center" style="margin-left: 45%;">Сохранить</button>
            </form>
        {% else %}
            <div class="accordion accordion-flush">
                {% include 'application/includes/app_competencies_list.html' %}
            </div>
        {% endif %}
    {% endif %}
</div>

{% endblock %}

science_selection/application/templates/application/application_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Создание заявки
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}

<div class="w-50 bg-white list-group-item list-group-item-light border-top-0" style="margin-left: 25%;">
    <div class="row">
        <form action="{% url 'create_application' %}" class="form-horizontal" method="post" id="form-container">
            {% include 'includes/app_form_field_template.html' %}
        </form>
    </div>
</div>

<script src="{% static 'js/add_education_form.js' %}" type="text/javascript"></script>
{% endblock %}

science_selection/application/templates/application/application_detail.html
{% extends 'base.html' %}
{% load static %}
{% load application_extras %}
{% block title %}
Просмотр заявки
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}

<div class="container-fluid">
    <div class="row justify-content-end">
        <div class="col-6 bg-white list-group-item list-group-item-light border-top-0">
            <div class="text-center">
                <h4 class=""> {{ app.member }}</h4>
            </div>
            <div class="d-flex flex-row">
                {% if not app.is_final or user.member.is_master %}
                <a href="{%url 'edit_application' pk %}">
                    <button class="btn btn-outline-dark m-2">Редактировать</button>
                </a>
                {% endif %}
                <button class="btn btn-outline-secondary m-2"><a
                        href="{%url 'create_word_app' pk %}">
                    <img src="{% static 'images/word.svg' %}" alt="download file" width="20" height="20"></a>
                </button>
                {% if user.member.is_moderator %} {% get_is_unsuitable_switch application=app %} {% endif %}
                {% get_is_final_switch application=app user=user%}
                {% if user.member.is_master %}
                {% include 'application/includes/book_button_template.html' %}
                {% include 'application/includes/wishlist_button_template.html' %}
                {% endif %}
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    <h5 class="text-center mb-3">Основная информация</h5>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Телефон:
                        </div>
                        <div class="col">
                            {{ app.member.phone }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Email:
                        </div>
                        <div class="col">
                            {{ app.member.user.email }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Дата рождения:
                        </div>
                        <div class="col">
                            {{ app.birth_day }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Место рождения:
                        </div>
                        <div class="col">
                            {{ app.birth_place }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Национальность:
                        </div>
                        <div class="col">
                            {{ app.nationality }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2 {% if user.member.is_master and not app.check_military_commissariat %} bg-danger text-dark bg-opacity-25 rounded{% endif %}">
                        <div class="col">
                            Военный комиссариат:
                        </div>
                        <div class="col">
                            {{ app.military_commissariat }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Группа здоровья:
                        </div>
                        <div class="col">
                            {{ app.group_of_health }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Год призыва:
                        </div>
                        <div class="col">
                            {{ app.draft_year }}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Сезон призыва:
                        </div>
                        <div class="col">
                            {{ app.get_draft_season_display }}
                        </div>
                    </div>
                </li>
                {% if user_education %}
                    <li class="list-group-item">
                        <h5 class="text-center mb-3">Образование</h5>
                        {% for educate in user_education %}
                        <div class="card text-center mb-1">
                            <div class="card-header"><h6>{{ educate.get_education_type_display }}</h6></div>
                            <div class="card-body text-dark">
                                <p class="card-title {% if user.member.is_master and not educate.check_name_uni %} bg-danger text-dark bg-opacity-25 rounded{% endif %}">
                                    Университет: {{ educate.university }}</p>
                                <p class="card-text">Специальнсть: {{ educate.specialization }} </p>
                                <p class="card-text">Средний балл: {{ educate.avg_score }}</p>
                                <p class="card-text">Наименование документа: {{ educate.name_of_education_doc }}</p>
                                <p class="card-text">Тема диплома: {{ educate.theme_of_diploma }}</p>
                                <p class="card-text">Год окончания: {{ educate.end_year }}</p>
                                <p class="card-text">Статус окончия: {% if educate.is_ended %}Окончил
                                    {% else %}Не окончил{% endif %}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </li>
                {% endif %}
                <li class="list-group-item mb-2">
                    <h5 class="text-center mb-3">Дополнительная информация</h5>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Готовность к секретности:
                        </div>
                        <div class="col">
                            {% if app.ready_to_secret %}Готов{% else %}Не готов{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Достижения:
                        </div>
                        <div class="col">
                            {% if app.scientific_achievements %}{{ app.scientific_achievements|linebreaks }}
                            {% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Стипендии:
                        </div>
                        <div class="col">
                            {% if app.scholarships %}{{ app.scholarships|linebreaks }}{% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Кандидатские экзамены:
                        </div>
                        <div class="col">
                            {% if app.candidate_exams %}{{ app.candidate_exams|linebreaks }}
                            {% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Спортивные достижения:
                        </div>
                        <div class="col">
                            {% if app.sporting_achievements %}{{ app.sporting_achievements|linebreaks }}
                            {% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Хобби:
                        </div>
                        <div class="col">
                            {% if app.hobby %}{{ app.hobby|linebreaks }}{% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                    <div class="row col-12 mb-2">
                        <div class="col">
                            Дополнительная Информация:
                        </div>
                        <div class="col">
                            {% if app.other_information %}{{ app.other_information|linebreaks }}
                            {% else %}Отсутствуют{% endif %}
                        </div>
                    </div>
                </li>
            </ul>
            <svg width="40" height="40" fill="currentColor" onclick="history.back()" class="bi bi-arrow-left" viewBox="0 0 15 15" id="btn-back">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
            </svg>
        </div>
        <div class="col-3">
            {% if user.member.is_master %}
            {% get_application_note application=app user=user %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

science_selection/application/templates/application/application_direction_choose.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Выбор направлений
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}

{% if msg %}
  <div class="btn w-50 mt-2" style="margin-left: 25%">
    {{ msg }}
    <button type="button" class="btn btn-outline-primary">
      <a href="{% url name pk %}">Выбрать</a>
    </button>
  </div>

{% else %}
  <div class="w-50 bg-white list-group-item border-top-0" style="margin-left: 25%;">
    {% if error_msg %}
      <div class="alert alert-warning text-center" role="alert">
        {{ error_msg }}
      </div>
    {% endif %}
    {% if user.member.is_master %}
        <h5 class="text-center mb-2">Выбранные кандидатом направления</h5>
    {% elif user.member.is_slave %}
        <div class="text-center lead bg-info bg-opacity-10 mb-2 rounded">Выберите желаемые направления отбора <br> Максимальное количество направлений - 4</div>
    {% endif %}
    {% if not blocked %}
      <form action="{% url 'choose_app_direction' pk %}" method="POST">
        {% csrf_token %}
        {% include 'application/includes/app_directions_list.html' %}
        <button type="submit" class="w-10 mb-2 btn btn-outline-dark justify-content-center" style="margin-left: 45%;">Сохранить</button>
      </form>
    {% else %}
      {% include 'application/includes/app_directions_list.html' %}
    {% endif %}
  </div>
{% endif %}

{% endblock %}

science_selection/application/templates/application/application_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Редактирование заявки
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}
{% include 'application/includes/nav_app_template.html' %}

<div class="w-50 bg-white list-group-item list-group-item-light" style="margin-left: 25%;">
    <div class="row">
        <form action="{% url 'edit_application' pk %}" class="form-horizontal" method="post" id="form-container">
            {% include 'includes/app_form_field_template.html' %}
        </form>
    </div>
</div>

<script src="{% static 'js/add_education_form.js' %}" type="text/javascript"></script>
{% endblock %}