science_selection/engine/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from account.views import HomeMasterView, HomeView, HomeSlaveView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls')),
                  path('app/', include('application.urls')),
                  path('test/', include('testing.urls')),
                  path('', HomeView.as_view(), name='home'),
                  path('master/', HomeMasterView.as_view(), name='home_master'),
                  path('operator/', HomeSlaveView.as_view(), name='home_slave'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

science_selection/science_selection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('application.urls'))
]

science_selection/testing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CreateTestView.as_view(), name='create_test'),
    path('list/',  views.TestListView.as_view(), name='test_list'),
    path('results/',  views.TestResultsView.as_view(), name='test_results'),
    path('add/<int:direction_id>/', views.AddTestInDirectionView.as_view(), name='add_test'),
    path('exclude/<int:test_id>/<int:direction_id>/', views.ExcludeTestInDirectionView.as_view(), name='exclude_test'),
    path('<int:pk>/',  views.DetailTestView.as_view(), name='test'),
    path('<int:pk>/question/',  views.AddQuestionToTestView.as_view(), name='add_question_to_test'),
    path('<int:pk>/question/<int:question_id>/',  views.UpdateQuestionView.as_view(), name='update_question'),
    path('<int:pk>/question/<int:question_id>/delete/',  views.DeleteQuestionView.as_view(), name='delete_question'),
    path('<int:pk>/edit/',  views.EditTestView.as_view(), name='edit_test'),
    path('<int:pk>/delete/', views.DeleteTestView.as_view(), name='delete_test'),
    path('<int:pk>/result/', views.AddTestResultView.as_view(), name='add_test_result'),
    path('<int:pk>/result/<int:result_id>/', views.TestResultView.as_view(), name='test_result'),
    path('<int:pk>/result/<int:result_id>/word/', views.TestResultInWordView.as_view(), name='test_result_in_word'),
]

science_selection/testing/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from utils.constants import PSYCHOLOGICAL_TYPE_OF_TEST


class TypeOfTest(models.Model):
    """ Таблица с возможными типами тестов """

    name = models.CharField(max_length=128, verbose_name='Тип теста')

    class Meta:
        verbose_name = "Тип теста"
        verbose_name_plural = "Тип тестов"

    def __str__(self):
        return f'{self.name}'

    def is_psychological(self):
        return self.name == PSYCHOLOGICAL_TYPE_OF_TEST


class Test(models.Model):
    """ Таблица с тестами """

    name = models.CharField(max_length=128, verbose_name='Название теста')
    time_limit = models.IntegerField(verbose_name='Ограничение по времени (в мин.)', blank=True, null=True)
    description = models.CharField(max_length=256, verbose_name='Описание теста', blank=True)
    directions = models.ManyToManyField('application.Direction', verbose_name='Направления тестов', blank=True)
    creator = models.ForeignKey('account.Member', on_delete=models.CASCADE, verbose_name='Создатель теста')
    type = models.ForeignKey(TypeOfTest, on_delete=models.CASCADE, verbose_name='Тип теста')
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['create_date']
        verbose_name = "Тест"
        verbose_name_plural = "Тесты"

    def __str__(self):
        return f'{self.name}-{self.creator}'


def validate_result(value):
    if value > 100 or value < 0:
        raise ValidationError(_(f'Результат должен находиться от 0 до 100'))


class TestResult(models.Model):
    """ Таблица с результатами тестов пользователей """

    test_statuses = [
        (1, 'Не начат'),
        (2, 'Начат'),
        (3, 'Закончен'),
    ]
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name='Тесты', related_name='test_res')
    member = models.ForeignKey('account.Member', on_delete=models.CASCADE, verbose_name='Пользователь',
                               related_name='test_result')
    result = models.IntegerField(verbose_name='Результат тестирования', blank=True, validators=[validate_result])
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата начала теста')
    end_date = models.DateTimeField(blank=True, verbose_name='Дата окончания теста')
    status = models.IntegerField(choices=test_statuses, default=1, verbose_name='Статус теста')

    class Meta:
        ordering = ['pk']
        verbose_name = "Результаты теста"
        verbose_name_plural = "Результаты тестов"

    def __str__(self):
        return f'{self.test} {self.status}'


class Question(models.Model):
    """ Таблица с вопросами для тестов """

    type_of_question = [
        (1, 'Один вариант ответа'),
        (2, 'Несколько вариантов ответа'),
        (3, 'Без правильных вариантов')
    ]
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name='Номер теста')
    wording = models.CharField(max_length=256, verbose_name='Формулировка')
    question_type = models.IntegerField(choices=type_of_question, verbose_name='Количество вариантов')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Изображение')

    class Meta:
        ordering = ['pk']
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

    def __str__(self):
        return f'{self.test}-{self.wording}'


class Answer(models.Model):
    """ Таблица с вариантами ответов к вопросам """

    meaning = models.CharField(max_length=256, verbose_name='Ответ')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос',
                                 related_name='answer_options')
    is_correct = models.BooleanField(default=False, verbose_name='Правильный ответ')

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

    def __str__(self):
        return f'{self.meaning}'


class UserAnswer(models.Model):
    """ Таблица с вариантами ответов пользователей к вопросам """

    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    member = models.ForeignKey('account.member', on_delete=models.CASCADE, verbose_name='Пользователь')
    answer_option = models.JSONField(verbose_name='Варианты ответа')

    class Meta:
        ordering = ['pk']
        verbose_name = "Ответ пользователя"
        verbose_name_plural = "Ответы пользователя"

    def __str__(self):
        return f'{self.question} {self.answer_option}'

science_selection/testing/views.py
import datetime

from collections import defaultdict
from itertools import groupby
from operator import attrgetter

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied, BadRequest
from django.db.models import Prefetch
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import escape_uri_path
from django.views import View
from django.views.generic import DetailView
from django.views.generic.list import ListView

from application.models import Application, Direction
from application.mixins import OnlyMasterAccessMixin, MasterDataMixin, OnlySlaveAccessMixin
from application.utils import WordTemplate, get_cleared_query_string_of_page, get_form_data
from utils.calculations import get_current_draft_year
from utils.exceptions import MasterHasNoDirectionsException
from utils.constants import PATH_TO_PSYCHOLOGICAL_TESTS

from .forms import TestCreateForm, QuestionForm, AnswerFormSetExtra1, AnswerFormSetExtra5, FilterTestResultForm
from .mixins import TestAndQuestionMixin
from .models import Test, TestResult, Question, UserAnswer, Answer
from .utils import get_master_directions


class TestListView(LoginRequiredMixin, View):
    """ Список всех тестов закрепленных за пользователем (либо оператором, либо офицером) """

    def get(self, request):
        context = self.get_user_context(self.request.user.member)
        return render(request, 'testing/test_list.html', context=context)

    def get_user_context(self, member):
        """ Создает контекст для шаблона страницы в зависимости от роли пользователя master/slave """
        context = {}
        if member.is_master():
            master_directions = [aff.direction for aff in member.affiliations.prefetch_related('direction').all()]
            if not master_directions:
                raise MasterHasNoDirectionsException(
                    f'У вас нет ни одного направления, по которому вы можете добавлять тесты')

            selected_direction = self.get_chosen_direction()
            selected_direction = master_directions[0] if not selected_direction and master_directions else selected_direction
            direction_tests = Test.objects.filter(directions=selected_direction).prefetch_related('creator').distinct()
            test_list = Test.objects.exclude(pk__in=direction_tests).prefetch_related('creator')
            context.update({
                'directions': master_directions,
                'selected_direction': selected_direction,
                'test_list': test_list,
                'direction_tests': direction_tests})
        elif member.is_slave():
            user_app = Application.objects.filter(member=member).prefetch_related('directions').first()
            if user_app:
                directions = user_app.directions.all()
                test_list = Test.objects.filter(directions__in=directions).prefetch_related(
                    Prefetch('test_res', queryset=TestResult.objects.filter(member=member))).distinct()
                context['directions'] = directions
                context['test_list'] = test_list
                if not user_app.directions.all().exists():
                    context['msg'] = 'Выберите направления в заявке'
            else:
                context['msg'] = 'Создайте заявку'
        return context

    def get_chosen_direction(self):
        """
        Получает выбранное направление по его Id из query параметра
        query: direction - int - id выбранного направления пользователя
        """
        selected_direction_id = self.request.GET.get('direction')
        return Direction.objects.get(id=int(selected_direction_id)) if selected_direction_id else None


class AddTestInDirectionView(MasterDataMixin, View):
    """ Добавляет выбранные тесты в направление """

    def post(self, request, direction_id):
        """
        Получает выбранные тесты из query параметра и закрепляет их за выбранным направлением
        query: chosen_test - list[int] - ids выбранных тестов
        """
        if direction_id not in self.get_master_directions_id():
            raise PermissionDenied('Невозможно добавить тест в чужое направление')
        chosen_test = request.POST.getlist('chosen_test')
        for test in Test.objects.filter(pk__in=chosen_test).prefetch_related('directions'):
            test.directions.add(direction_id)
        return redirect(reverse('test_list') + f'?direction={direction_id}')


class ExcludeTestInDirectionView(MasterDataMixin, View):
    """ Удалить тест из выбранного направления """

    def get(self, request, test_id, direction_id):
        """ Получает тест по его Id и открепляет его из выбранного направления """
        if direction_id not in self.get_master_directions_id():
            raise PermissionDenied('Невозможно удалить тест из чужого направления')
        test = Test.objects.filter(pk=test_id).prefetch_related('directions').first()
        test.directions.remove(direction_id)
        return redirect(reverse('test_list') + f'?direction={direction_id}')


class TestResultsView(LoginRequiredMixin, OnlyMasterAccessMixin, ListView):
    """ Получить список результатов тестирования операторов """
    model = TestResult
    template_name = 'testing/test_results.html'
    paginate_by = 50

    def get_queryset(self):
        apps = Application.objects.select_related('member').only('member')
        current_apps = self._get_filtered_queryset(apps)
        members = [app.member for app in current_apps]
        return TestResult.objects.filter(member__in=members).prefetch_related('test', 'member', 'test__type').order_by('member')

    def _get_filtered_queryset(self, apps):
        """Фильтруует список анкет по году и сезону призыва. Если приходят пустые параметры, то текущий год и призыв"""
        if not get_form_data(self.request.GET):
            current_year, current_season = get_current_draft_year()
            return apps.filter(draft_year=current_year, draft_season=current_season[0])

        draft_season = self.request.GET.getlist('draft_season', None)
        if draft_season:
            apps = apps.filter(draft_season__in=draft_season).distinct()

        # фильтрация по году призыва
        draft_year = self.request.GET.getlist('draft_year', None)
        if draft_year:
            apps = apps.filter(draft_year__in=draft_year).distinct()
        return apps

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        args = get_form_data(self.request.GET)

        results = {member: list(tests) for member, tests in groupby(context['testresult_list'], attrgetter('member'))}
        context['results'] = results

        current_year, current_season = get_current_draft_year()
        initial = {
            'draft_year': current_year,
            'draft_season': current_season,
        }
        draft_year_set = Application.objects.order_by('draft_year').distinct().values_list('draft_year', 'draft_year')
        filter_form = FilterTestResultForm(initial=initial, data=args, draft_year_set=draft_year_set,)
        context['form'] = filter_form
        context['reset_filters'] = True if args else False
        context['cleaned_query_string'] = get_cleared_query_string_of_page(self.request.META['QUERY_STRING'])
        return context


class CreateTestView(LoginRequiredMixin, OnlyMasterAccessMixin, View):
    """ Создание нового теста постоянным составом """

    def get(self, request):
        directions = get_master_directions(self.request.user)
        test_form = TestCreateForm(directions=directions)
        context = {'test_form': test_form}
        return render(request, 'testing/test_create.html', context=context)

    def post(self, request):
        """ Получает и проверяет данные формы для создания теста, после чего сохраняет ее """
        directions = get_master_directions(self.request.user)
        test_form = TestCreateForm(directions, request.POST)
        if test_form.is_valid():
            new_test = test_form.save(commit=False)
            new_test.creator = request.user.member
            new_test.save()
            test_form.save_m2m()
            return redirect('test', pk=new_test.pk)
        else:
            errors = [str(v[0].message) for _, v in test_form.errors.as_data().items()]
            context = {'msg': '; '.join(errors), 'test_form': test_form}
            return render(request, 'testing/test_create.html', context=context, status=400)


class DeleteTestView(TestAndQuestionMixin):
    """ Удалить тест по его id (может только создатель) """

    def get(self, request, pk):
        test = self._get_and_check_test_permission(pk, request.user.member)
        test.delete()
        return redirect('test_list')


class DetailTestView(LoginRequiredMixin, DetailView):
    """ Просмотр данных теста """

    model = Test
    template_name = 'testing/test_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member = self.request.user.member
        user_test = TestResult.objects.filter(test=context['test'].pk, member=member).first()
        if user_test and (timezone.now() > user_test.end_date or user_test.status == TestResult.test_statuses[-1][0]):
            context['msg'] = 'Тест завершен'
            context['blocked'] = True
            if user_test.status != TestResult.test_statuses[-1][0]:
                TestResult.objects.filter(test=context['test'].pk, member=member) \
                    .update(status=TestResult.test_statuses[-1][0])
        context['questions'] = Question.objects.filter(test=context['test']).only('wording')
        return context


class AddQuestionToTestView(TestAndQuestionMixin):
    """ Добавить вопрос к тесту """

    def get(self, request, pk):
        test = self._get_and_check_test_permission(pk, request.user.member)

science_selection/testing/templates/testing/add_test_result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Решение
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}

<div class="w-50 bg-white list-group-item list-group-item-light" style="margin-left: 25%;">
    <div class="row">
        <h4 class="text-center">Вопросы к тесту - {{ test.name }}</h4>
        <p class="fs-5 offset-1 mb-1 col-10"><b class="text-primary text-opacity-75">Описание:</b> {{ test.description }}</p>

        {% if not test.type.is_psychological or test.time_limit %}
            <div id="countdown" class="countdown fs-5 fst-italic">
                <div class="text-end">Оставшееся время:
                    <span class="hours"></span>:<span class="minutes"></span>:<span class="seconds "></span>
                </div>
            </div>
        {% endif %}

        {% if msg %}
            <div class="alert alert-danger">{{ msg }}</div>
        {% endif %}

        <form action="{% url 'add_test_result' test.pk %}" class="form-horizontal" method="post" id="form-container">
            {% csrf_token %}
            <ul class="list-group list-group-flush list-group-numbered">
            {% for question in question_list %}
                <li class="mb-1 list-group-item">
                    <span class="fs-5 text-primary text-opacity-75">{{ question.wording }}</span>
                    {% if question.image %}
                        <div class="col-6 offset-3">
                            <img src="{{ question.image.url }}" class="card-img-top">
                        </div>
                    {% endif %}
                    <div class="container">
                        <div class="row row-cols-2">
                        {% for answer in question.answer_options.all %}
                            <div class="col-4 offset-2">
                                {% if question.question_type == 1 or test.type.is_psychological %}
                                    <input class="form-check-input" type="radio" name="answer_{{ question.id }}_"
                                           value="{{ answer.pk }}" {% if answer.pk in user_answers %}checked{%endif%}>
                                {% else %}
                                    <input class="form-check-input" type="checkbox" name="answer_{{question.id}}_{{ answer.pk }}">
                                {%endif%}
                                {{ answer }}
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </li>
            {% endfor %}
            </ul>
            <div class="mb-2 text-center">
                <button type="submit" class="btn btn-outline-dark">Сохранить</button>
            </div>
        </form>
    </div>
</div>

{% if not test.type.is_psychological or test.time_limit %}
    {{ end_date|json_script:"end_time" }}
    <script src="{% static 'js/add_form_timer.js' %}" type="text/javascript"></script>
{% endif %}
{% endblock %}

science_selection/testing/templates/testing/test_result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Результат теста
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-6 bg-white list-group-item list-group-item-light">
            <div class="text-center">
                <h4 class="">Ответы к тесту - {{ test_res.test.name }}</h4>
            </div>
            <p class="fs-5 offset-1 mb-0 col-10"><b class="text-primary text-opacity-75">Пользователь:</b> {{ test_res.member }}</p>
            <p class="fs-5 offset-1 mb-0 col-10"><b class="text-primary text-opacity-75">Описание:</b> {{ test_res.test.description }}</p>
            {% if is_psychological %}
                <div class="d-flex justify-content-end">
                    <button class="btn btn-outline-secondary mb-2"><a href="{% url 'test_result_in_word' pk result_id %}">
                        <img src="{% static 'images/word.svg' %}" alt="download file" width="20" height="20"></a>
                    </button>
                </div>
            {% endif %}
            <ul class="list-group list-group-flush">
                {% for question in question_list %}
                    <li class="list-group-item mb-1">
                        <div class="text-center fw-bold">
                            {{ question.wording }}
                        </div>
                        {% if question.image %}
                            <div class="col-6 offset-3">
                                <img src="{{ question.image.url }}" class="card-img-top">
                            </div>
                        {% endif %}
                        <div class="row row-cols-2 mb-2">
                            {% for answer in question.answer_options.all %}
                                <div class="col mb-2 text-center
                                    {% if is_psychological and answer.pk in user_answers or answer.pk in user_answers and answer.is_correct %}
                                        text-success
                                    {% elif answer.pk in user_answers %}
                                        text-danger
                                    {% endif %}">
                                    {{ answer.meaning }}
                                </div>
                            {% endfor %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

science_selection/testing/templates/testing/test_results.html
{% extends 'base.html' %}
{% load static %}
{% load testing_extras %}
{% block title %}
Результаты тестирования
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <h4 class="text-center mb-3">Результаты тестирования</h4>

        <div class="col-2 mb-3 bg-white position-relative">
            <h5>
                Фильтры
            </h5>
            {% if reset_filters %}
                <a class="nav-link position-absolute top-0 end-0 text-nowrap" href=" {% url 'test_results' %} ">Сбросить фильтры</a>
            {% endif %}
            <form method="get">
                {% include 'includes/get_form_field_template.html' %}
                <div class="mt-2 mb-2 text-center">
                    <button type="submit" class="btn btn-outline-dark">Применить</button>
                </div>
            </form>
        </div>

        <div class="col-6">
            <table class="table bg-white">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <td scope="col">ФИО</td>
                        <td scope="col">Название теста</td>
                        <td scope="col">Тип теста</td>
                        <td scope="col">Результат теста, %</td>
                        <td scope="col">Статус теста</td>
                        <td scope="col">Отчет</td>
                    </tr>
                </thead>
                <tbody>
                    {% for member, res in results.items %}
                        {% if res|length > 1 %}
                            <tr>
                                <th rowspan="{{res|length}}">
                                    {{ forloop.counter }}
                                </th>
                                <td rowspan="{{res|length}}" scope="row" class="text-nowrap">
                                    {{ member }}
                                </td>
                                {% for test in res %}
                                    {% if forloop.first %}
                                        <td scope="row" class="text-nowrap">
                                            {{ test.test.name }}
                                        </td>
                                        <td scope="row" class="text-nowrap">
                                            {{ test.test.type }}
                                        </td>
                                        <td scope="row" class="text-nowrap">
                                            {% if not test.test.type.is_psychological %}{{ test.result }}{% endif %}
                                        </td>
                                        <td scope="row" class="text-nowrap">
                                            {{ test.get_status_display }}
                                        </td>
                                        <td scope="row" class="text-nowrap">
                                            <a href="{% url 'test_result' test.test.pk test.pk %}">Подробнее</a>
                                        </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td scope="row" class="text-nowrap">
                                                {{ test.test.name }}
                                            </td>
                                            <td scope="row" class="text-nowrap">
                                                {{ test.test.type }}
                                            </td>
                                            <td scope="row" class="text-nowrap">
                                                {% if not test.test.type.is_psychological %}{{ test.result }}{% endif %}
                                            </td>
                                            <td scope="row" class="text-nowrap">
                                                {{ test.get_status_display }}
                                            </td>
                                            <td scope="row" class="text-nowrap">
                                                <a href="{% url 'test_result' test.test.pk test.pk %}">Подробнее</a>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                        {% else %}
                            <tr>
                                <th>
                                    {{ forloop.counter }}
                                </th>
                                <td scope="row" class="text-nowrap">
                                    {{ member }}
                                </td>
                                {% for test in res %}
                                    <td scope="row" class="text-nowrap">
                                        {{ test.test.name }}
                                    </td>
                                    <td scope="row" class="text-nowrap">
                                        {{ test.test.type }}
                                    </td>
                                    <td scope="row" class="text-nowrap">
                                        {% if not test.test.type.is_psychological %}{{ test.result }}{% endif %}
                                    </td>
                                    <td scope="row" class="text-nowrap">
                                        {{ test.get_status_display }}
                                    </td>
                                    <td scope="row" class="text-nowrap">
                                        <a href="{% url 'test_result' test.test.pk test.pk %}">Подробнее</a>
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            {% include 'application/includes/pagination_template.html' %}
        </div>
    </div>
</div>

{% endblock %}

science_selection/testing/templates/testing/testing_list.html
{% extends 'base.html' %}
{% load static %}
{% load testing_extras %}
{% block title %}
Список тестов
{% endblock %}
{% block content %}
{% include 'includes/header_template.html' %}

<div class="w-50 bg-white list-group-item list-group-item-light" style="margin-left: 25%;">
    <h4 class="text-center mb-3">Список тестов</h4>
    {% if msg %}
        <div class="alert alert-info text-center">{{ msg }}</div>
    {% else %}
    <div class="container">
        {% if user.member.is_master %}
            <div class="mb-2">
                <a href="{% url 'create_test' %}">Добавить тест</a>
            </div>
        {% endif %}
        {% for test in testing_list %}
            <div class="row justify-content-between mb-2">
                <div class="col-6">
                    <h6>
                        {% if test.test_res.all.0.status == 2 %}
                            <a href="{% url  'add_test_result' test.pk %}">{{test.name}}</a>
                        {% else %}
                            <a href="{% url 'test'  test.pk %}">{{test.name}}</a>
                        {% endif %}
                    </h6>
                </div>
                {% if user.member.is_slave %}
                    {% if test.test_res.all.0.status == 3 and not test.type.is_psychological %}
                        <div class="col-3">
                            Результат: {{test.test_res.all.0.result|default:"0" }}
                        </div>
                    {% endif %}
                    <div class="col-3">
                        Статус: {{test.test_res.all.0.get_status_display|default:"Не начат" }}
                    </div>
                {% elif user.member.is_master and test.creator.pk == user.member.pk %}
                    <div class="col-1">
                        <button type="button" class="btn ms-3 p-1" data-bs-toggle="modal" aria-label="delete" data-bs-target="#deleteTestModal{{ test.pk }}">
                                <img src="{% static 'images/trash.svg' %}" alt="Удалить" width="20" height="20">
                        </button>
                        {% get_delete_test_modal test=test %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {% endif %}

</div>

{% endblock %}